runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /tasks/.*
  script: main.app
  login: admin
  auth_fail_action: unauthorized

- url: /.*
  script: main.app

libraries:
 - name: jinja2
   version: latest
